name: Node.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  node:16-alpine

    services:
      postgres:
        image: postgres:12-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: starter
          POSTGRES_PASSWORD: starter

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn run lint
      - name: Migrate database
        run: yarn run db:migrate
        env:
          NODE_ENV: test
          DB_NAME: starter
          DB_USER: postgres
          DB_PASSWORD: starter
          DB_HOST: postgres
      - name: Test
        run: yarn run test
        env:
          NODE_ENV: test
          DB_NAME: starter
          DB_USER: postgres
          DB_PASSWORD: starter
          DB_HOST: postgres
          JWT_SECRET_KEY: supersecretkey
      - name: Build
        run: yarn run build
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist
